### ISSUE TITLE
✨ 포트폴리오 상세 페이지 구현

### ISSUE THREAD

**Issue by rlafl7942** [hit-it-PDA/FE#14]
## 📌 Description
- 포트폴리오 상세 페이지 구현

## 📝 To-do
- [x] 상세 정보 UI
- [x] 상품 비중 UI
- [x] 종목 구성 UI
