### ISSUE TITLE
🐛 전체적인 디자인 및 css 오류 수정

### ISSUE THREAD

**Issue by rlafl7942** [hit-it-PDA/FE#44]
## 📌 Description
- 전체적인 디자인 및 css 오류 수정

## 📝 To-do
- [x] #45
- [x] 노후준비종합진단 버튼 기본 값 버그 수정
- [x] 마이데이터 연결 시 버튼이 항목 가림 이슈 수정
- [x] 투자성향테스트 후, 로딩 화면 추가
- [ ] 회원가입 시, 입력 항목 나올 때마다 애니메이션 추가
- [x] 홈 화면 필터링 버튼 제거
- [x] 하단 바 아이콘 색 변경
