### ISSUE TITLE
♻️ 라우터 연결 및 상단/하단 바 수정

### ISSUE THREAD

**Issue by rlafl7942** [hit-it-PDA/FE#8]
## 📌 Description
- 각 하단 바에 연결되는 화면마다 레이아웃 생성 후, 라우터 다시 연결하고 화면마다 상단/하단 바 수정

## 📝 To-do
- [x] 홈 레이아웃 생성 및 라우터 연결
- [x] 포트폴리오 레이아웃 생성 및 라우터 연결
- [x] 자산 레이아웃 생성 및 라우터 연결
- [ ] 각 화면마다 사용할 상단바, 하단바 수정

**Comment by rlafl7942** [comment]
depth가 0이 아닌 페이지에서 탭을 누르면 depth가 0인 페이지로 돌아가도록 수정해야할 것 같아요.
